on:
  push:
    branches:
      - '**' # Matches all branches

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Ensure Hugo is installed
        uses: peaceiris/actions-hugo@v4
        with:
          hugo-version: "latest"